AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MIB Converter App

Parameters:
  NewRelicAccountId:
    Type: String
  NewRelicLicenseKey:
    Type: String

Resources:
  # S3 Bucket for MIB files
  MibBucket:
    Type: AWS::S3::Bucket

  # Lambda Function
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: run.sh
      Runtime: python3.9
      Timeout: 180
      MemorySize: 512
      Architectures: [x86_64]
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap        
          bucket_name: !Ref MibBucket
          NEW_RELIC_ACCOUNT_ID: !Ref NewRelicAccountId
          NEW_RELIC_LICENSE_KEY: !Ref NewRelicLicenseKey
          NEW_RELIC_APP_NAME: "MIB-Converter-Lambda"
          NEW_RELIC_LAMBDA_HANDLER: "app.app"
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref MibBucket
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "*"
      Events:
        HttpApi:
          Type: HttpApi

Outputs:
  ApiUrl:
    Description: "API Endpoint"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"