AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MIB Converter App with Background Sync

Parameters:
  NewRelicAccountId: { Type: String }
  NewRelicLicenseKey: { Type: String }

Resources:
  # 1. コンテンツ格納用テーブル
  KentikProfileCache:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: KentikProfileCache
      AttributeDefinitions:
        - AttributeName: path
          AttributeType: S
      KeySchema:
        - AttributeName: path
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # 2. 定期同期用 Lambda (1時間ごとに数件ずつ更新)
  SyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: sync.lambda_handler
      Runtime: python3.12
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          GITHUB_SECRET_ID: "prod/github/token"
          CACHE_TABLE_NAME: !Ref KentikProfileCache
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref KentikProfileCache
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/github/token-*"
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: "rate(1 hour)" # 1時間ごとに実行

  # 3. メインの Flask Lambda
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: newrelic_lambda_wrapper.handler
      Runtime: python3.12
      Timeout: 180
      MemorySize: 2048
      Layers:
        - arn:aws:lambda:ap-northeast-1:451483290750:layer:NewRelicPython312:58
      Environment:
        Variables:
          NEW_RELIC_LAMBDA_HANDLER: app.lambda_handler
          NEW_RELIC_ACCOUNT_ID: !Ref NewRelicAccountId
          NEW_RELIC_LICENSE_KEY: !Ref NewRelicLicenseKey
          NEW_RELIC_APP_NAME: "MIB-Converter-Lambda"
          GITHUB_SECRET_ID: "prod/github/token"
          CACHE_TABLE_NAME: !Ref KentikProfileCache
      Policies:
        - DynamoDBReadPolicy: # アプリは読み取りのみ
            TableName: !Ref KentikProfileCache
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "*"
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: any